### ISSUE TITLE
Downstream patches from Forgeflower

### ISSUE THREAD

**Issue by jaskarth** [Vineflower/vineflower#288]
- [x] Standardization of floating point https://github.com/MinecraftForge/ForgeFlower/commit/66188184f4fdbca1de547424f76f21ae5c360ef6
- [x] JAD param renaming https://github.com/MinecraftForge/ForgeFlower/commit/39c9a516f3819a0e70603fc94977d2948a6203f4
- [x] Fix lambdas not respecting JAD param naming https://github.com/MinecraftForge/ForgeFlower/commit/816ed8d0ed16a6c62b820d94bdff65529770ba1d
- [x] Fix variables in finally blocks not getting renamed https://github.com/MinecraftForge/ForgeFlower/pull/105
